[deploy]
bucket = 'cfn-artifacts-space'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cruddur.space'
EnvBackendUrl = 'https://api.cruddur.space'
DDBMessageTable = 'CrdDdb-DynamoDBTable-JSMEXA263TZ9'