image:
  file: .gitpod.Dockerfile
  
github:
  prebuilds:    
    master: true    
    branches: false   
    pullRequests: true    
    pullRequestsFromForks: false    
    addCheck: true    
    addComment: false    
    addBadge: false

tasks:
  - name: Workspace Initialization
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i      
      cd $THEIA_WORKSPACE_ROOT
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/backend-flask/bin/rds/rds-sg-update"
  - name: fargate
    before: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      cd backend-flask
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
